# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18KA-poed8b3lJoUkIhDqGnnTlzMHvyLu
"""

import streamlit as st
import joblib
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

# Load the trained model and vectorizer
model = joblib.load("spam_model.pkl")
vectorizer = joblib.load("tfidf_vectorizer.pkl")

# Text preprocessing function
nltk.download('stopwords')
stemmer = PorterStemmer()
stop_words = set(stopwords.words('english'))

def clean_text(text):
    text = re.sub(r'\W', ' ', text)  # Remove special characters
    text = text.lower()  # Convert to lowercase
    text = text.split()  # Tokenize
    text = [stemmer.stem(word) for word in text if word not in stop_words]  # Remove stopwords & apply stemming
    return " ".join(text)

def predict_email(text):
    cleaned_text = clean_text(text)
    text_vectorized = vectorizer.transform([cleaned_text]).toarray()
    prediction = model.predict(text_vectorized)
    return "🚨 Spam Email" if prediction[0] == 1 else "✅ Not Spam Email"

# Streamlit UI
st.title("📧 Email Spam Detection App")
st.write("Enter an email message below to check if it's Spam or Not.")

# Input from user
user_input = st.text_area("Enter Email Content:", "")

if st.button("Check Spam"):
    if user_input:
        result = predict_email(user_input)
        st.subheader(result)
    else:
        st.warning("Please enter some email text to check.")

